# Generated by Django 5.1.6 on 2025-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Unused'), (2, 'Incorrect'), (3, 'Marked'), (4, 'Omited'), (5, 'Correct')], default=1),
        ),
    ]
