# Generated by Django 5.1.8 on 2025-04-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_alter_useranswer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranswer",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Unused"),
                    (2, "Incorrect"),
                    (3, "Marked"),
                    (4, "Omitted"),
                    (5, "Correct"),
                ],
                default=1,
            ),
        ),
    ]
