# Generated by Django 5.1.6 on 2025-04-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
    ]
