# Generated by Django 5.1.8 on 2025-04-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_remove_user_email_verified_at"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Suscription",
            new_name="Subscription",
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "University"),
                    (2, "Academy"),
                    (3, "School"),
                    (4, "Other"),
                ],
                default=4,
            ),
        ),
    ]
